### ISSUE TITLE
I got error

### ISSUE THREAD

**Issue by Gl1tch-studio** [MethaTrader/BuxTaskWorker#1]
Traceback (most recent call last):
  File "C:\Users\Gl1t4\Desktop\BuxTaskWorker-master\main.py", line 29, in <module>
    save("table.html", table.prettify()) #save page table with formatting
AttributeError: 'NoneType' object has no attribute 'prettify'

**Comment by MethaTrader** [comment]
You may not have entered your session data (cookies) into the seofast service. Therefore, it cannot find the table.

The bot at the moment is only able to parse all the tasks of a particular author (namely clicks in social networks). HE CAN NOT PERFORM TASKS.
